resampling-interval: 5000

gridSize:
    sampler-type: "uniform"
    min_value: 4
    max_value: 6

numObstacles:
    sampler-type: "uniform"
    min_value: 1
    max_value: 3

numGoals:
    sampler-type: "uniform"
    min_value: 1
    max_value: 3
