resampling-interval: 5000

block_scale:
    sampler-type: "uniform"
    min_value: 1.5
    max_value: 3

dynamic_friction:
    sampler-type: "uniform"
    min_value: 0.0
    max_value: 0.5

static_friction:
    sampler-type: "uniform"
    min_value: 0.0
    max_value: 0.5

block_drag:
    sampler-type: "uniform"
    min_value: 0.0
    max_value: 1.0
