resampling-interval: 5000

angle:
    sampler-type: "uniform"
    min_value: 45
    max_value: 55

gravity:
    sampler-type: "uniform"
    min_value: 8
    max_value: 10

scale:
    sampler-type: "uniform"
    min_value: 0.75
    max_value: 2
